early_stopping:
  early_stopping_patience: 3
  early_stopping_threshold: 0.001
general:
  data_path: data
  model_folder_name: kobart
  model_name: digit82/kobart-summarization
  output_dir: outputs
inference:
  batch_size: 32
  ckt_path: /root/upstageailab-nlp-summarization-nlp_7/outputs/kobart/checkpoint-1276
  early_stopping: true
  generate_max_length: 128
  no_repeat_ngram_size: 2
  num_beams: 4
  remove_tokens:
  - <usr>
  - <s>
  - </s>
  - <pad>
  result_path: outputs/prediction
tokenizer:
  bos_token: <s>
  decoder_max_len: 128
  encoder_max_len: 612
  eos_token: </s>
  special_tokens:
  - '#Address#'
  - '#CardNumber#'
  - '#CarNumber#'
  - '#DateOfBirth#'
  - '#Email#'
  - '#Name#'
  - '#PassportNumber#'
  - '#Person1#'
  - '#Person2#'
  - '#Person3#'
  - '#Person4#'
  - '#Person5#'
  - '#Person6#'
  - '#Person7#'
  - '#PersonName#'
  - '#PhoneNumber#'
  - '#Price#'
  - '#SSN#'
training:
  do_eval: true
  do_train: true
  evaluation_strategy: epoch
  fp16: true
  generation_max_length: 128
  greater_is_better: true
  learning_rate: 1.0e-05
  load_best_model_at_end: true
  logging_dir: ./logs
  logging_strategy: epoch
  lr_scheduler_type: cosine
  metric_for_best_model: eval_rouge_avg
  num_train_epochs: 20
  optim: adamw_torch
  overwrite_output_dir: true
  per_device_eval_batch_size: 16
  per_device_train_batch_size: 50
  predict_with_generate: true
  report_to: wandb
  save_strategy: epoch
  save_total_limit: 3
  seed: 42
  warmup_ratio: 0.1
  weight_decay: 0.01
wandb:
  entity: NLP-7
  project: baseline
